### ISSUE TITLE
Implement Logging

### ISSUE THREAD

**Issue by SaloniSS** [DSC-UTDallas/Agenda-Bot#25]
- Google Cloud Logging: https://cloud.google.com/logging/docs/setup/nodejs
- Sentry: https://docs.sentry.io/platforms/node/

**Comment by zeal-saloni-s** [comment]
Although Sentry is a popular logging tool, we have already configured GCP for this project so using that will keep all our utilities under one roof. @ReshmiCode Whats your option on this?  Should we try each out and then decide what to use or should we just decide on one platform from the start and go for it (if yes, which one?

**Comment by ReshmiCode** [comment]
From a quick look at the GCP one, it seems easy to use and we gotta stick to Google brand (even they don't stick to their own)
