### ISSUE TITLE
Connect GCP Alert Notifications to Discord

### ISSUE THREAD

**Issue by SaloniSS** [DSC-UTDallas/Agenda-Bot#30]
- [x] GCP Monitoring Notifications
  - https://github.com/Courtsite/stackdriver-to-discord
- [x]  GCP Logging Errors
- [x] GCP Billing Notifications
  - https://medium.com/google-cloud/kill-unexpected-cloud-costs-integrate-gcp-budget-alerts-with-slack-microsoft-teams-hangouts-b1db306db080

**Comment by zeal-saloni-s** [comment]
I swear I’ll figure out how to do this someday

**Comment by zeal-saloni-s** [comment]
I think I figured out how to do this o_0
