### ISSUE TITLE
Connect google forms

### ISSUE THREAD

**Issue by SaloniSS** [DSC-UTDallas/Agenda-Bot#31]
- https://github.com/Iku/Google-Forms-to-Discord
- Could be used to create a marketing request form and ping marketing whenever we have a request

**Comment by zeal-saloni-s** [comment]
https://docs.google.com/document/d/11sSs_VM-E1UWDJuXfCd1laSNeLCpIZhxmdIwAXInlLs/edit

**Comment by SaloniSS** [comment]
https://docs.google.com/document/d/11sSs_VM-E1UWDJuXfCd1laSNeLCpIZhxmdIwAXInlLs/edit
